server:
  port: 8084
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:13306/memos
    username: memos
    password: memos
  docker:
    compose:
      lifecycle-management: start_and_stop
      file: ./compose.yaml
app:
  secret: 111
  refresh: 111
  mode: dev
