style:
  MagicNumber:
    ignoreNumbers:
      - '1'
      - '2'
      - '3'
      - '4'
      - '5'
      - '6'
      - '7'
      - '8'
      - '9'
      - '0'
      - '1024'
    ignoreEnums: true
    ignorePropertyDeclaration: true
  ThrowsCount:
    active: false

complexity:
  LongMethod:
    excludes: '**/*Routes.kt'
