openapi: "3.1.0"
info:
  title: "spring_mono API"
  description: "spring_mono API"
  version: "1.0.0"
servers:
  - url: "http://127.0.0.1:8080"
paths:
  /api/v1/auth:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "111"
  /api/v1/auth/signin:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignIn"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Pair_? extends String"
  /api/v1/auth/signup:
    post:
      description: ""
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignUp"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    SignIn:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
        neverExpire:
          type: "boolean"
          nullable: true
      required:
        - "username"
        - "password"
    Pair:
      type: "object"
      properties: { }
    Pair_? extends String:
      type: "object"
      properties:
        first:
          type: "object"
        second:
          type: "object"
    SignUp:
      type: "object"
      properties:
        username:
          type: "string"
        password:
          type: "string"
      required:
        - "username"
        - "password"
